# Default values for redis-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Default values for pika-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# if useLegacyCompDef is false ,cluster will be rendered by component definition rather than componentDefRef in cluster definition
useLegacyCompDef: true

nameOverride: ""
fullnameOverride: ""

groupCount: 3

slaveCount: 1

etcdReplicaCount: 3

codisProxyReplicaCount: 2

codisFeReplicaCount: 1

codisDashboardReplicaCount: 1

terminationPolicy: Delete

clusterVersionOverride: ""

monitor:
  enabled: true

switchPolicy:
  type: Noop

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  pikaGroup:
    limits:
      cpu: 8000m
      memory: 10Gi
    requests:
      cpu: 8000m
      memory: 10Gi
  etcd:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 2000m
      memory: 1Gi
  pikaExporter:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 2000m
      memory: 4Gi
  codisProxy:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 2000m
      memory: 4Gi
  codisFe:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 2000m
      memory: 4Gi
  codisDashboard:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 2000m
      memory: 4Gi

persistence:
  enabled: true
  pikaData:
    storageClassName:
    size: 50Gi
  etcdData:
    storageClassName:
    size: 10Gi

topologyKeys:
  - kubernetes.io/hostname

## @param tolerations
## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: [ ]

#enabledLogs:
#  - running

# The RBAC permission used by cluster component pod, now include event.create
serviceAccount:
  name: ""

etcdAddrs: "etcd-0.etcd-headless.default.svc.cluster.local:2379,etcd-1.etcd-headless.default.svc.cluster.local:2379,etcd-2.etcd-headless.default.svc.cluster.local:2379"
